on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      APP_NAME: "Geostatystyka"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      APP_DIR: "_book"
      RSCONNECT_URL: ${{ secrets.RSCONNECT_URL }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Prep all
        run: |
          chmod +x _build.sh _publish.sh

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e "install.packages('remotes')"
          R -e "install.packages('rsconnect')"
          R -e "install.packages('tinytex')"
          R -e "install.packages('rmarkdown')"
          R -e "tinytex::install_tinytex()"
          R -e "remotes::install_github('nowosad/geostatbook')"
          R -e "install.packages('curl')"
          R -e "install.packages('latex2exp')"
          R -e "install.packages(c('bslib', 'downlit', 'xml2'))"
          R -e "install.packages('renv')"
          R -e "renv::restore()"

      - name: Build site
        run: |
          ./_build.sh

      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}

      - name: Deploy to RStudio Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ env.RSCONNECT_APIKEY }}@${{ env.RSCONNECT_URL }}
          access-type: logged_in
          show-logs: true
          force: true
          dir: ${{ env.APP_DIR }}
          require-vanity-path: true
          
      # - name: Publish site
      #   run: |
      #     ./_publish.sh
  
