on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      APP_NAME: "Geostatystyka"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      APP_DIR: "Geostatystyka"
      RSCONNECT_URL: ${{ secrets.RSCONNECT_URL }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Prep all
        run: |
          chmod +x _build.sh _publish.sh

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Cache bookdown results
        uses: actions/cache@v1
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Build site
        run: |
          ./_build.sh

      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}

      - name: Deploy to RStudio Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ env.RSCONNECT_APIKEY }}@${{ env.RSCONNECT_URL }}
          access-type: all
          show-logs: true
          force: true
          dir: ${{ env.APP_DIR }}
          require-vanity-path: true
          
      # - name: Publish site
      #   run: |
      #     ./_publish.sh
  
